// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxr_3oyhvLCAQtUp3p9FE160bRunxfj-k',
    appId: '1:892718162528:web:40a2fc5430c37ba8959905',
    messagingSenderId: '892718162528',
    projectId: 'daira-e405d',
    authDomain: 'daira-e405d.firebaseapp.com',
    storageBucket: 'daira-e405d.firebasestorage.app',
    measurementId: 'G-198YG6QZNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABECfDAabynGpkD9CbAxMzd5gt0Cqy05k',
    appId: '1:892718162528:android:c2541dbb82d4b011959905',
    messagingSenderId: '892718162528',
    projectId: 'daira-e405d',
    storageBucket: 'daira-e405d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRlssvKAdQVP_QlPpf30GU6qYF5mbgK4',
    appId: '1:892718162528:ios:f4288af7b7801a61959905',
    messagingSenderId: '892718162528',
    projectId: 'daira-e405d',
    storageBucket: 'daira-e405d.firebasestorage.app',
    iosBundleId: 'com.example.daira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcRlssvKAdQVP_QlPpf30GU6qYF5mbgK4',
    appId: '1:892718162528:ios:f4288af7b7801a61959905',
    messagingSenderId: '892718162528',
    projectId: 'daira-e405d',
    storageBucket: 'daira-e405d.firebasestorage.app',
    iosBundleId: 'com.example.daira',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxr_3oyhvLCAQtUp3p9FE160bRunxfj-k',
    appId: '1:892718162528:web:c227b4c429663ec4959905',
    messagingSenderId: '892718162528',
    projectId: 'daira-e405d',
    authDomain: 'daira-e405d.firebaseapp.com',
    storageBucket: 'daira-e405d.firebasestorage.app',
    measurementId: 'G-RVDX4ZMXGW',
  );

}